const coolants = [
  {
    coolant_type: "R-744",
    formula: "CO2",
    gwp: 1,
    restricted: "No",
    notes: "Used as a refrigerant (R-744).",
  },
  {
    coolant_type: "HFC-23",
    formula: "CHF3",
    gwp: 12400,
    restricted: "Phase-out",
    notes: "A refrigerant (R-23), often used in low-temperature applications.",
  },
  {
    coolant_type: "HFC-32",
    formula: "CH2F2",
    gwp: 677,
    restricted: "No",
    notes: "A refrigerant, used as a replacement for R-22.",
  },
  {
    coolant_type: "HFC-41",
    formula: "CH3F",
    gwp: 116,
    restricted: "No",
    notes: "A refrigerant, though not as commonly used.",
  },
  {
    coolant_type: "HFC-125",
    formula: "CHF2CF3",
    gwp: 3170,
    restricted: "Restricted",
    notes: "Used in blends for refrigeration and air conditioning.",
  },
  {
    coolant_type: "HFC-134a",
    formula: "CH2FCF3",
    gwp: 1300,
    restricted: "Restricted",
    notes: "Common refrigerant (R-134a), widely used in automotive air conditioning and other systems.",
  },
  {
    coolant_type: "HFC-143a",
    formula: "CH3CF3",
    gwp: 4800,
    restricted: "No",
    notes: "Refrigerant blend.",
  },
  {
    coolant_type: "HFC-152",
    formula: "CH2FCH2F",
    gwp: 16,
    restricted: "No",
    notes: "A refrigerant, often used as a component in refrigerant blends.",
  },
  {
    coolant_type: "HFC-152a",
    formula: "CH3CHF2",
    gwp: 138,
    restricted: "No",
    notes: "Used as a refrigerant, and as a propellant.",
  },
  {
    coolant_type: "HFC-161",
    formula: "CH3CH2F",
    gwp: 4,
    restricted: "No",
    notes: "A refrigerant with potential as a low-GWP option.",
  },
  {
    coolant_type: "HFC-227ea",
    formula: "CF3CHFCF3",
    gwp: 3350,
    restricted: "No",
    notes: "A fire suppressant and refrigerant.",
  },
  {
    coolant_type: "HFC-236cb",
    formula: "CH2FCF2CF3",
    gwp: 1210,
    restricted: "No",
    notes: "Used in fire suppression and refrigeration.",
  },
  {
    coolant_type: "HFC-236ea",
    formula: "CHF2CHFCF3",
    gwp: 1330,
    restricted: "No",
    notes: "Similar to HFC-236cb, used for refrigeration and fire suppression.",
  },
  {
    coolant_type: "HFC-236fa",
    formula: "CF3CH2CF3",
    gwp: 8060,
    restricted: "No",
    notes: "Used in fire suppression and refrigeration.",
  },
  {
    coolant_type: "HFC-245ca",
    formula: "CH2FCF2CHF2",
    gwp: 716,
    restricted: "No",
    notes: "Used in refrigeration and air conditioning systems.",
  },
  {
    coolant_type: "HFC-245fa",
    formula: "CHF2CH2CF3",
    gwp: 858,
    restricted: "No",
    notes: "Used in refrigeration and air conditioning systems.",
  },
  {
    coolant_type: "HFC-365mfc",
    formula: "CH3CF2CH2CF3",
    gwp: 804,
    restricted: "No",
    notes: "A refrigerant in some commercial applications.",
  },
  {
    coolant_type: "R-401A",
    formula: "53% HCFC-22 , 34% HCFC-124 , 13% HFC-152a",
    gwp: 18,
    restricted: "No",
    notes: "A refrigerant blend, often used as a replacement for CFC-based refrigerants.",
  },
  {
    coolant_type: "R-401B",
    formula: "61% HCFC-22 , 28% HCFC-124 , 11% HFC-152a",
    gwp: 15,
    restricted: "No",
    notes: "Refrigerant blend.",
  },
  {
    coolant_type: "R-401C",
    formula: "33% HCFC-22 , 52% HCFC-124 , 15% HFC-152a",
    gwp: 21,
    restricted: "No",
    notes: "A refrigerant blend for refrigeration systems.",
  },
  {
    coolant_type: "R-402A",
    formula: "38% HCFC-22 , 60% HFC-125 , 2% propane",
    gwp: 1902,
    restricted: "No",
    notes: "Refrigerant blend.",
  },
  {
    coolant_type: "R-402B",
    formula: "60% HCFC-22 , 38% HFC-125 , 2% propane",
    gwp: 1205,
    restricted: "No",
    notes: "Refrigerant blend.",
  },
  {
    coolant_type: "R-403B",
    formula: "56% HCFC-22 , 39% PFC-218 , 5% propane",
    gwp: 3471,
    restricted: "No",
    notes: "A blend of refrigerants used in refrigeration.",
  },
  {
    coolant_type: "R-404A",
    formula: "44% HFC-125 , 4% HFC-134a , 52% HFC-143a",
    gwp: 3943,
    restricted: "Restricted",
    notes: "A widely used refrigerant for commercial refrigeration.",
  },
  {
    coolant_type: "R-406A",
    formula: "55% HCFC-22 , 41% HCFC-142b , 4% isobutane",
    gwp: 0,
    restricted: "No",
    notes: "A refrigerant blend used in older systems.",
  },
  {
    coolant_type: "R-407A",
    formula: "20% HFC-32 , 40% HFC-125 , 40% HFC-134a",
    gwp: 1923,
    restricted: "No",
    notes: "A refrigerant blend used in air conditioning and refrigeration.",
  },
  {
    coolant_type: "R-407B",
    formula: "10% HFC-32 , 70% HFC-125 , 20% HFC-134a",
    gwp: 2547,
    restricted: "No",
    notes: "Refrigerant blend.",
  },
  {
    coolant_type: "R-407C",
    formula: "23% HFC-32 , 25% HFC-125 , 52% HFC-134a",
    gwp: 1624,
    restricted: "Restricted",
    notes: "A common refrigerant blend, widely used as a replacement for R-22.",
  },
  {
    coolant_type: "R-407D",
    formula: "15% HFC-32 , 15% HFC-125 , 70% HFC-134a",
    gwp: 1487,
    restricted: "No",
    notes: "A refrigerant blend used for refrigeration.",
  },
  {
    coolant_type: "R-408A",
    formula: "47% HCFC-22 , 7% HFC-125 , 46% HFC-143a",
    gwp: 2430,
    restricted: "No",
    notes: "A refrigerant blend used in some refrigeration systems.",
  },
  {
    coolant_type: "R-409A",
    formula: "60% HCFC-22 , 25% HCFC-124 , 15% HCFC-142b",
    gwp: 0,
    restricted: "No",
    notes: "Used in refrigeration systems.",
  },
  {
    coolant_type: "R-410A",
    formula: "50% HFC-32 , 50% HFC-125",
    gwp: 1924,
    restricted: "Phase-out",
    notes: "A popular refrigerant blend for air conditioning.",
  },
  {
    coolant_type: "R-410B",
    formula: "45% HFC-32 , 55% HFC-125",
    gwp: 2048,
    restricted: "No",
    notes: "A refrigerant blend used in air conditioning and heat pump systems.",
  },
  {
    coolant_type: "R-411A",
    formula: "87.5% HCFC-22 , 11% HFC-152a , 1.5% propylene",
    gwp: 15,
    restricted: "No",
    notes: "Refrigerant blend.",
  },
  {
    coolant_type: "R-411B",
    formula: "94% HCFC-22 , 3% HFC-152a , 3% propylene",
    gwp: 4,
    restricted: "N/A",
    notes: "Refrigerant blend.",
  },
  {
    coolant_type: "R-414A",
    formula: "51% HCFC-22 , 28.5% HCFC-124 , 16.5% HCFC-142b , 4% isobutane",
    gwp: 0,
    restricted: "N/A",
    notes: "Refrigerant blend.",
  },
  {
    coolant_type: "R-414B",
    formula: "50% HCFC-22 , 39% HCFC-124 , 9.5% HCFC-142b , 1.5% isobutane",
    gwp: 0,
    restricted: "N/A",
    notes: "Refrigerant blend.",
  },
  {
    coolant_type: "R-417A",
    formula: "46.6% HFC-125 , 50% HFC-134a , 3.4% butane",
    gwp: 2127,
    restricted: "N/A",
    notes: "A blend used in refrigeration systems.",
  },
  {
    coolant_type: "R-422A",
    formula: "85.1% HFC-125 , 11.5% HFC-134a , 3.4% isobutane",
    gwp: 2847,
    restricted: "Restricted",
    notes: "A refrigerant blend used as a replacement for R-22.",
  },
  {
    coolant_type: "R-422D",
    formula: "65.1% HFC-125 , 31.5% HFC-134a , 3.4% isobutane",
    gwp: 2473,
    restricted: "N/A",
    notes: "A refrigerant blend used as a retrofit for R-22 systems.",
  },
  {
    coolant_type: "R-424A",
    formula: "50.5% HFC-125 , 47% HFC-134a , 1% butane , 0.9% isobutane , 0.6% isopentane",
    gwp: 3104,
    restricted: "N/A",
    notes: "Refrigerant blend.",
  },
  {
    coolant_type: "R-426A",
    formula: "5.1% HFC-125 , 93% HFC-134a , 1.3% butane , 0.6% isobutane",
    gwp: 1371,
    restricted: "N/A",
    notes: "Refrigerant blend.",
  },
  {
    coolant_type: "R-428A",
    formula: "77.5% HFC-125 , 20% HFC-143a , 1.9% isobutane , 0.6% propane",
    gwp: 3417,
    restricted: "Restricted",
    notes: "Refrigerant blend.",
  },
  {
    coolant_type: "R-434A",
    formula: "63.2% HFC-125 , 16% HFC-134a , 18% HFC-143a , 2.8% isobutane",
    gwp: 3075,
    restricted: "Restricted",
    notes: "Refrigerant blend.",
  },
  {
    coolant_type: "R-507A",
    formula: "50% HFC-125 , 50% HFC-143a",
    gwp: 3985,
    restricted: "Restricted",
    notes: "A widely used refrigerant, especially in commercial refrigeration.",
  },
  {
    coolant_type: "R-508A",
    formula: "39% HFC-23 , 61% PFC-116",
    gwp: 11607,
    restricted: "Restricted",
    notes: "Refrigerant blend.",
  },
  {
    coolant_type: "R-508B",
    formula: "46% HFC-23 , 54% PFC-116",
    gwp: 11698,
    restricted: "Restricted",
    notes: "Refrigerant blend.",
  },
];

export async function seed(knex) {

  await knex("coolant_types").del();
  await knex("coolant_types").insert(coolants);
}
